apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database-svc
spec:
  ports:
  - name: "tcp-5432"
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
