apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: teslamate
  name: teslamate
spec:
  ports:
  - name: "http-4000"
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    io.kompose.service: teslamate
status:
  loadBalancer: {}
